### ISSUE TITLE
4.md; Spoiler!! section; 1st code sample, line 2

### ISSUE THREAD

**Issue by figueroadavid** [concentrateddon/powershell-by-mistake#1]
The existing section reads:
```
PS C:\> $a = 'Hello'
PS C:\> $b = "$a, World'
PS C:\> $b
Hello, World
```
The second line should read (the end of the line should have a double quote instead of a single quote):
```
PS C:\> $b = "$a, World"
```

David F.

**Comment by concentrateddon** [comment]
Please feel free to submit a pull request as a fix ;).

**Comment by figueroadavid** [comment]
Making the pull request as requested..
